#!/bin/bash
# Copyright (C) 2026 by Henry Kroll III, www.thenerdshow.com
#
# With code contributions by Matthew Rensberry
#
# This is free software.  You may redistribute it under the terms
# of the Apache license and the GNU General Public License Version
# 2 or at your option any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
if [[ "$1" == "-h" ]]; then echo <<EOF "\
usage: `basename $0` [lang] [mimic3 ops]   example: `basename $0` es_ES/m-ailabs_low -s karen_savage
    See 'mimic3 --voices' for a full list.
    Use 'mimic3-download [lang]' to get them."
EOF
exit 0
fi

# default to en_US
lang="${1:-en_US}"
# fifo queue to hold temporary audio file names
audio_fifo=$(mktemp); rm "$audio_fifo" ; mkfifo "$audio_fifo"
# start whisper service
systemctl --user start whisper.service 2>/dev/null

## create a trap to remove temp files, stop server on untimely exit
cleanup() {
    systemctl --user stop whisper.service 2>/dev/null
    rm -f /tmp/tmp.txt "$audio_fifo"
}
trap cleanup 0

# function to process audio files from queue
trans(){
    while read audio; do
        # Send audio file to whisper.cpp using curl
        curl_output=$(curl -s "http://127.0.0.1:7777/inference" \
                        -H "Content-Type: multipart/form-data" \
                        -F "file=@$audio" \
                        -F "temperature=0.2" \
                        -F "language=${lang/_*}" \
                        -F "response-format=json")

        # Parse JSON to extract text
        extracted_text=$(echo "$curl_output" | jq -r '.text')

        # remove temporary audio file
        rm -f "$audio"

        # print in colored text, if terminal supports it (man ascii)
        if [[ "$TERM" =~ ^xterm|^screen|^linux|^rxvt|^vt100|^ansi|^xterm-256color ]]
        then echo -e "\033[33m${extracted_text}\033[0m"
        else echo "$extracted_text"
        fi

        # Thanks for watching! seems to occur frequently due to noise.
        if [[ ! "$extracted_text" =~ "Thanks for watching!" ]] \
            && [[ "$extracted_text" != *'['* ]]; then
             # send audio to default (headphone if plugged-in)
             # If it doesn't work, use `aplay -L` to list devices
            mimic3 --voice "$lang" "$@" "$extracted_text" \
            --stdout|aplay --device sysdefault:CARD=Generic
        fi &
    done < "$audio_fifo"
    #cleanup
    rm -f "$audio_fifo"
}

# record audio in background
while true; do
    # Make temporary files to hold audio
    tmp=$(mktemp)
    # Remove it on exit
    trap 'rm "$tmp" ; exit' INT

    # Listen to the mic.
    # The `1 0.2 4%` part of this command trims one clip of silence
    # from the beginning. 4% of max volume is considered silence here.
    # `1 1.0 2%` stops after a 1.0 second pause in speech.
    # If recording never stops, increase sound threshold from 2%
    # to 5% or more. This can happen with poor recording equipment
    # or noisy environments with heaters and fans going.

    rec --guard --norm -c 1 -r 22050 -t mp3 "$tmp" silence 1 0.2 6% 1 1.0 5%

    # echo temporary audio file name to transcription queue
    echo "$tmp"
done > "$audio_fifo" & #The `&` lets recording run in the background.

# run audio transciption handler
trans "${@:2}"
